# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    match(type: "appstore")
    build_app(workspace: "iOS-todoApp.xcworkspace", scheme: "iOS-todoApp")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
  lane :increase_build_number do
      identifier = get_info_plist_value(path: "./iOS-todoApp/Info.plist", key: "CFBundleVersion")
      new_identifier = (identifier.to_i + 1).to_s
      set_info_plist_value(path: "./iOS-todoApp/Info.plist", key: "CFBundleVersion", value: new_identifier)
      puts("버전 넘버" + identifier + "가 " + new_identifier + "로 변경 되었습니다.")
  end
end
